### ISSUE TITLE
Selecting rename in the menu doesn't do anything?

### ISSUE THREAD

**Issue by scottchiefbaker** [Fleshgrinder/rutorrent-rename#1]
I installed `rename` in my plugins folder. Now I see a "rename" option in my right-click context menu. Clicking this new menu item doesn't do anything though... how do I troubleshoot further why clicking doesn't do anything?

I'm running the latest Firefox if it matters.

**Comment by Fleshgrinder** [comment]
Debugging in ruTorrent is a pain, the only way is through adding `console.log` everywhere. I fixed it, I overlooked the superfluous `'` in the action string for the context menu handler and didn’t catch it while testing manually because I always used <kbd>F2</kbd>. 😋 

Thanks for reporting! ❤️

**Comment by scottchiefbaker** [comment]
That fixed my problem!
